-- El Gordo Stock: weekly shared shopping list
create table if not exists public.shopping_list (
  id bigint generated by default as identity primary key,
  restaurant text not null check (restaurant in ('union','jersey')),
  category text not null check (category in ('Kitchen','Back','Front')),
  item text not null,
  qty numeric not null,
  unit text not null default '',
  week_start date not null,
  created_at timestamptz not null default now()
);

alter table public.shopping_list enable row level security;

create policy "public read shopping list"
on public.shopping_list
for select
to anon, authenticated
using (true);

create policy "public insert shopping list"
on public.shopping_list
for insert
to anon, authenticated
with check (true);

create policy "public delete shopping list"
on public.shopping_list
for delete
to anon, authenticated
using (true);

grant select, insert, delete
on public.shopping_list
to anon, authenticated;

grant usage, select
on sequence public.shopping_list_id_seq
to anon, authenticated;

-- Realtime: add shopping_list to the supabase_realtime publication.
do $$
begin
  alter publication supabase_realtime add table public.shopping_list;
exception
  when duplicate_object then null;
end $$;
